config:
  target: "http://64.176.226.236:8080"
  processor: "./processor.js"
  phases:
    - duration: 30
      arrivalRate: 2
      name: warmup
    - duration: 30
      arrivalRate: 2
      rampTo: 8
      name: ramup
    - duration: 30
      arrivalRate: 8
      name: sustained
    - duration: 30
      arrivalRate: 8
      rampTo: 2
      name: end-of-load

scenarios:
  - name: "order and pay"
    flow:
      - function: "setUser"
      - function: "setProduct"
      - function: "setOrder"
      - function: "setPay"

      - post:
          url: "/api/order"
          headers:
            Content-Type: application/json
            X-MOCK-USER-LOGINID: "{{ loginId }}"
          json:
            orderName: "{{ orderName }}"
            orderId: "{{ orderId }}"
            orderCreates:
              - productId: "{{ productId }}"
                stockQuantity: 1
          capture:
            - json: "$.totalAmount"
              as: "amount"
      - post:
          url: "/api/payment"
          headers:
            Content-Type: application/json
            X-MOCK-USER-LOGINID: "{{ loginId }}"
          json:
            orderId: "{{ orderId }}"
            paymentKey: "{{ paymentKey }}"
            amount: "{{ amount }}"