config:
  target: "http://64.176.226.236:8080"
  processor: "./OrderAndPayProcessor.js"
  phases:
    - duration: 20
      arrivalRate: 5
      name : wamrup
    - duration : 20
      arrivalRate: 5
      rampTo : 8
      name : rampup
    - duration : 30
      arrivalRate : 8
      name : sustained
    - duration : 20
      arrivalRate: 8
      rampTo : 5
      name : end of load

scenarios:
  - name: "pay"
    flow:
      - function: "setSequentialIds"
      - function: "setPay"
      - post:
          name: "payment_api"
          url: "/api/payment"
          headers:
            Content-Type: application/json
            X-MOCK-USER-LOGINID: "{{ loginId }}"
          json:
            orderId: "{{ orderId }}"
            paymentKey: "{{ paymentKey }}"
            amount: 1000
          afterResponse : "logResponse"