config:
  target: "http://64.176.226.236:8080"
  processor: "./OrderAndPayProcessor.js"
  phases:
    - duration: 20
      arrivalRate: 100

scenarios:
  - name: "order"
    flow:
      - function: "setUser"
      - function: "setProduct"
      - function: "setOrder"

      - post:
          url: "/api/order"
          headers:
            Content-Type: application/json
            X-MOCK-USER-LOGINID: "{{ loginId }}"
          json:
            orderName: "{{ orderName }}"
            orderId: "{{ orderId }}"
            orderCreates:
              - productId: "{{ productId }}"
                stockQuantity: 1
          capture:
            - json: "$.totalAmount"
              as: "amount"