config:
  target: "http://64.176.226.236:8080"
  processor: "./OrderAndPayProcessor.js"
  phases:
    - duration: 20
      arrivalRate: 2

scenarios:
  - name: "order and pay"
    flow:
      - function: "setUser"
      - function: "setProduct"
      - function: "setOrder"
      - function: "setPay"

      - post:
          url: "/api/order"
          name: "order_api"
          headers:
            Content-Type: application/json
            X-MOCK-USER-LOGINID: "{{ loginId }}"
          json:
            orderName: "{{ orderName }}"
            orderId: "{{ orderId }}"
            orderCreates:
              - productId: "{{ productId }}"
                stockQuantity: 1
          capture:
            - json: "$.totalAmount"
              as: "amount"

      - think: 0.3

      - post:
          name: "payment_api"
          url: "/api/payment"
          headers:
            Content-Type: application/json
            X-MOCK-USER-LOGINID: "{{ loginId }}"
          json:
            orderId: "{{ orderId }}"
            paymentKey: "{{ paymentKey }}"
            amount: "{{ amount }}"