config:
  target: "http://64.176.226.236:8080"
  processor: "./processor.js"
  phases:
    - duration: 30
      arrivalRate: 5
      name: Warm up
    - duration: 30
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 30
      arrivalRate: 10
      rampTo: 5
      name: End of load

scenarios:
  - name: "order test"
    flow:
      - function: "setUser"
      - function: "setProduct"
      - function: "setOrder"

      - post:
          url: "/api/order"
          headers:
            Content-Type: application/json
            X-MOCK-USER-LOGINID: "{{ loginId }}"
          json:
            orderName: "{{ orderName }}"
            orderId: "{{ orderId }}"
            orderCreates:
              - productId: "{{ productId }}"
                stockQuantity: 1