package jongwon.e_commerce.mock;

import jongwon.e_commerce.common.exception.ResourceNotFoundException;
import jongwon.e_commerce.product.domain.Product;
import jongwon.e_commerce.product.repository.ProductRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeProductRepository implements ProductRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Product> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Product save(Product product) {
        if (product.getProductId() == null || product.getProductId() == 0) {
            Product newProduct = Product.builder()
                    .productId(autoGeneratedId.incrementAndGet())
                    .productName(product.getProductName())
                    .productPrice(product.getProductPrice())
                    .productStatus(product.getProductStatus())
                    .stockQuantity(product.getStockQuantity())
                    .build();

            data.add(newProduct);
            return newProduct;
        } else {
            data.removeIf(item -> Objects.equals(item.getProductId(), product.getProductId()));
            data.add(product);
            return product;
        }
    }

    @Override
    public Optional<Product> findById(Long id) {
        return data.stream().filter(item -> item.getProductId().equals(id)).findAny();
    }

    @Override
    public Product getById(Long id) {
        return findById(id).orElseThrow(
                () -> new ResourceNotFoundException("Product", id)
        );
    }

    public void clearData(){
        data.clear();
    }
}
