package jongwon.e_commerce.mock.fake;

import jongwon.e_commerce.common.exception.ResourceNotFoundException;
import jongwon.e_commerce.payment.domain.Pay;
import jongwon.e_commerce.payment.domain.detail.MPPay;
import jongwon.e_commerce.payment.repository.MPPayRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMPPayRepository implements MPPayRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<MPPay> data = Collections.synchronizedList(new ArrayList<>());
    @Override
    public MPPay save(MPPay mpPay) {
        if(mpPay.getId() == null || mpPay.getId() == 0){
            MPPay newItem = MPPay.builder().
                    id(autoGeneratedId.incrementAndGet()).
                    pay(mpPay.getPay()).
                    customerMobilePhone(mpPay.getCustomerMobilePhone()).
                    receiptUrl(mpPay.getReceiptUrl()).settlementStatus(mpPay.getSettlementStatus()).
                    build();
            data.add(mpPay);
            return newItem;
        } else{
            data.removeIf(item -> Objects.equals(item.getId(), mpPay.getId()));
            data.add(mpPay);
            return mpPay;
        }
    }

    @Override
    public Optional<MPPay> findByPay(Pay pay) {
        return data.stream()
                .filter(item -> item.getPay() != null)
                .filter(item -> Objects.equals(item.getPay().getId(), pay.getId()))
                .findAny();
    }

    @Override
    public MPPay getByPay(Pay pay) {
        return findByPay(pay).orElseThrow(
                () -> new ResourceNotFoundException("Does not Exist mpPay of PayId:", pay.getId())
        );
    }
}
