package jongwon.e_commerce.mock.fake;

import jongwon.e_commerce.common.exception.ResourceNotFoundException;
import jongwon.e_commerce.order.domain.Order;
import jongwon.e_commerce.order.repository.OrderRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeOrderRepository implements OrderRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Order> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Order save(Order order) {
        if (order.getId() == null || order.getId() == 0) {
            Order newOrder = Order.builder()
                    .id(autoGeneratedId.incrementAndGet())
                    .member(order.getMember())
                    .orderId(order.getOrderId())
                    .orderName(order.getOrderName())
                    .orderStatus(order.getOrderStatus())
                    .totalAmount(order.getTotalAmount())
                    .orderedAt(order.getOrderedAt())
                    .build();

            data.add(newOrder);
            return newOrder;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), order.getId()));
            data.add(order);
            return order;
        }
    }

    @Override
    public Order getById(Long id) {
        return findById(id).orElseThrow(
                () -> new ResourceNotFoundException("Order", id)
        );
    }

    @Override
    public Order getByOrderId(String orderId) {
        return findByOrderId(orderId).orElseThrow(
                () -> new ResourceNotFoundException("Order", orderId)
        );
    }

    @Override
    public Optional<Order> findById(Long id) {
        return data.stream()
                .filter(order -> Objects.equals(order.getId(), id))
                .findAny();
    }

    @Override
    public Optional<Order> findByOrderId(String orderId) {
        return data.stream()
                .filter(order -> Objects.equals(order.getOrderId(), orderId))
                .findAny();
    }

    public void clearData(){
        data.clear();
    }
}
