package jongwon.e_commerce.mock.fake;

import jongwon.e_commerce.order.domain.Order;
import jongwon.e_commerce.order.domain.OrderItem;
import jongwon.e_commerce.order.repository.OrderItemRepository;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakeOrderItemRepository implements OrderItemRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<OrderItem> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public OrderItem save(OrderItem orderItem) {
        if (orderItem.getOrderItemId() == null || orderItem.getOrderItemId() == 0) {
            OrderItem newItem = OrderItem.builder()
                    .orderItemId(autoGeneratedId.incrementAndGet())
                    .product(orderItem.getProduct())
                    .productName(orderItem.getProductName())
                    .orderPrice(orderItem.getOrderPrice())
                    .orderQuantity(orderItem.getOrderQuantity())
                    .order(orderItem.getOrder())
                    .build();

            data.add(newItem);
            return newItem;
        } else {
            data.removeIf(item -> Objects.equals(item.getOrderItemId(), orderItem.getOrderItemId()));
            data.add(orderItem);
            return orderItem;
        }
    }

    @Override
    public List<OrderItem> findByOrderId(Long orderId) {
        return data.stream()
                .filter(item -> item.getOrder() != null)
                .filter(item -> Objects.equals(item.getOrder().getId(), orderId))
                .toList();
    }

}
