package jongwon.e_commerce.mock.fake;

import jongwon.e_commerce.common.exception.ResourceNotFoundException;
import jongwon.e_commerce.payment.domain.Pay;
import jongwon.e_commerce.payment.domain.PayRequest;
import jongwon.e_commerce.payment.repository.PayRequestRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakePayRequestRepository implements PayRequestRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<PayRequest> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public PayRequest save(PayRequest payRequest) {
        if(payRequest.getId() == null || payRequest.getId() == 0){
            PayRequest newPayRequest = PayRequest.builder().
                    id(autoGeneratedId.incrementAndGet()).
                    payAmount(payRequest.getPayAmount()).
                    payStatus(payRequest.getPayStatus()).
                    order(payRequest.getOrder()).
                    paymentKey(payRequest.getPaymentKey()).
                    pgType(payRequest.getPgType()).build();
            data.add(newPayRequest);
            return newPayRequest;
        }else{
            data.removeIf(item -> Objects.equals(item.getId(), payRequest.getId()));
            data.add(payRequest);
            return payRequest;
        }
    }

    @Override
    public Optional<PayRequest> findById(long id) {
        return data.stream().filter(payRequest -> Objects.equals(payRequest.getId(), id))
                .findAny();
    }

    @Override
    public PayRequest getById(Long id) {
        return findById(id).orElseThrow(
                () -> new ResourceNotFoundException("PayRequest", id)
        );
    }

    @Override
    public Optional<PayRequest> findByPaymentKey(String paymentKey) {
        return data.stream().filter(payRequest -> Objects.equals(payRequest.getPaymentKey(), paymentKey))
                .findAny();
    }

    @Override
    public PayRequest getByPaymentKey(String paymentKey) {
        return findByPaymentKey(paymentKey).orElseThrow(
                () -> new ResourceNotFoundException("PayRequest", paymentKey)
        );
    }
}
