package jongwon.e_commerce.mock.fake;

import jongwon.e_commerce.payment.domain.detail.MPPay;
import jongwon.e_commerce.payment.repository.MPPayRepository;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMPPayRepository implements MPPayRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<MPPay> data = Collections.synchronizedList(new ArrayList<>());
    @Override
    public MPPay save(MPPay mpPay) {
        if(mpPay.getId() == null || mpPay.getId() == 0){
            MPPay newItem = MPPay.builder().
                    id(autoGeneratedId.incrementAndGet()).
                    pay(mpPay.getPay()).
                    customerMobilePhone(mpPay.getCustomerMobilePhone()).
                    receiptUrl(mpPay.getReceiptUrl()).settlementStatus(mpPay.getSettlementStatus()).
                    build();
            data.add(mpPay);
            return newItem;
        } else{
            data.removeIf(item -> Objects.equals(item.getId(), mpPay.getId()));
            data.add(mpPay);
            return mpPay;
        }
    }
}
