package jongwon.e_commerce.mock.fake;

import jongwon.e_commerce.common.exception.ResourceNotFoundException;
import jongwon.e_commerce.payment.domain.Pay;
import jongwon.e_commerce.payment.repository.PaymentRepository;
import jongwon.e_commerce.product.domain.Product;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakePaymentRepository implements PaymentRepository {
    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Pay> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Pay save(Pay pay) {
        if(pay.getId() == null || pay.getId() == 0){
            Pay newPay = Pay.builder().
                    id(autoGeneratedId.incrementAndGet()).
                    order(pay.getOrder()).
                    payAmount(pay.getPayAmount()).
                    payMethod(pay.getPayMethod()).
                    payStatus(pay.getPayStatus()).
                    approvedAt(pay.getApprovedAt()).
                    paymentKey(pay.getPaymentKey()).build();

            data.add(newPay);
            return newPay;
        }else{
            data.removeIf(item -> Objects.equals(item.getId(), pay.getId()));
            data.add(pay);
            return pay;
        }
    }

    @Override
    public Optional<Pay> findById(long id) {
        return data.stream().filter(pay -> Objects.equals(pay.getId(), id))
                .findAny();
    }

    @Override
    public Pay getById(Long id) {
        return findById(id).orElseThrow(
                () -> new ResourceNotFoundException("Pay", id)
        );
    }

    @Override
    public Optional<Pay> findByPaymentKey(String paymentKey) {
        return data.stream().filter(pay -> Objects.equals(pay.getPaymentKey(), paymentKey))
                .findAny();
    }

    @Override
    public Pay getByPaymentKey(String paymentKey) {
        return findByPaymentKey(paymentKey).orElseThrow(
                () -> new ResourceNotFoundException("Pay", paymentKey)
        );
    }
}
