package jongwon.e_commerce.mock.fake;

import jongwon.e_commerce.common.exception.ResourceNotFoundException;
import jongwon.e_commerce.member.domain.Member;
import jongwon.e_commerce.member.repository.MemberRepository;
import jongwon.e_commerce.order.domain.OrderItem;
import jongwon.e_commerce.payment.domain.detail.MPPay;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeMemberRepository implements MemberRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(0);
    private final List<Member> data = Collections.synchronizedList(new ArrayList<>());


    @Override
    public Member getById(long id) {
        return findById(id).orElseThrow(
                () ->  new ResourceNotFoundException("member", id)
        );
    }

    @Override
    public Member save(Member member) {
        if (member.getMemberId() == null || member.getMemberId() == 0) {
            Member newMember = Member.builder()
                    .memberId(autoGeneratedId.incrementAndGet())
                    .memberName(member.getMemberName())
                    .email(member.getEmail())
                    .addr(member.getAddr())
                    .password(member.getPassword())
                    .loginId(member.getLoginId())
                    .build();

            data.add(newMember);
            return newMember;
        } else {
            data.removeIf(item -> Objects.equals(item.getMemberId(), member.getMemberId()));
            data.add(member);
            return member;
        }
    }

    @Override
    public Optional<Member> findById(Long id) {
        return data.stream()
                .filter(member -> Objects.equals(member.getMemberId(), id))
                .findAny();
    }
}
